name: Bandit

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
jobs:
  bandit_check:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install bandit==1.7.2
    - name: Run Bandit
      run: python -m bandit -r ./ -f screen
      working-directory: .