name: Linters

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
        python -m pip install -r requirements.txt
    - name: Run flake8
      id: flake8
      run: python -m flake8 --max-line-length=140 --ignore=E265,F403,F405,E126 ./
      continue-on-error: true
      working-directory: .
    - name: Run pylint
      id: pylint
      run: python -m pylint --max-line-length=140 **/*.py --output-format=colorized
      continue-on-error: true
      working-directory: .
    - name: Run mypy
      id: mypy
      run: python -m mypy --namespace-packages ./
      continue-on-error: true
      working-directory: .
    - name: Check on failures
      if: steps.flake8.outcome != 'success' || steps.pylint.outcome != 'success' || steps.mypy.outcome != 'success'
      run: exit 1