name: Linters

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt
    - name: Run flake8
      run: python -m flake8 ./
      continue-on-error: true
      working-directory: .
    - name: Run pylint
      run: python -m pylint **/*.py --output-format=colorized
      continue-on-error: true
      working-directory: .
    - name: Run mypy
      run: python -m mypy ./
      continue-on-error: true
      working-directory: .